locations:
  dataIn: «root»/data/published-init
  dataOut: «root»/published
  cssOut: «root»/published/css/style.css
  viewers: «root»/data/viewers
  binDir: «root»/bin
  partialsIn: «client»/design/components
  templates: «client»/design/templates
  texts: «client»/design/texts
  images: «client»/design/images
  js: «client»/design/js
  cssIn: «client»/design/css/input.css

markdown:
  keys:
    - abstract
    - description
    - provenance

listKeys:
  keys:
    - creator
    - contributor
    - institution
    - place
    - period
    - subject

generation:
  allprojects:
    title: "Pure3D Projects"
  alleditions:
    title: "Pure3D Editions"

viewers:
  default: voyager
  voyager:
    element: voyager-explorer
