locations:
  dataIn: «root»/data/published/input
  dataOut: «root»/data/published/dist
  cssOut: «root»/data/published/dist/css/style.css
  viewers: «root»/data/viewers
  binDir: «root»/bin
  partialsIn: «base»/design/components
  templates: «base»/design/templates
  texts: «base»/design/texts
  images: «base»/design/images
  js: «base»/design/js
  cssIn: «base»/design/css/input.css

markdown:
  keys:
    - abstract
    - description
    - provenance

list:
  keys:
    - creator
    - contributor
    - institution
    - place
    - period
    - subject

generation:
  allprojects:
    title: "Pure3D Projects"
  alleditions:
    title: "Pure3D Editions"

viewers:
  default: voyager
  voyager:
    element: voyager-explorer
